import { PrismaClient } from '@prisma/client';

const db = new PrismaClient();

interface SeedAssessment {
  name: string;
  slug: string;
  url: string;
  description: string;
  testType: string;
  category: string;
  remoteTesting: boolean;
  adaptive: boolean;
  duration: string;
  jobLevels: string;
  languages: string;
  skills: string;
}

const assessments: SeedAssessment[] = [
  // ============================================================================
  // COGNITIVE ABILITY TESTS (C)
  // ============================================================================
  {
    name: "Verify - Numerical Reasoning",
    slug: "verify-numerical-reasoning",
    url: "https://www.shl.com/products/product-catalog/view/verify-numerical-reasoning/",
    description: "Measures the ability to understand and evaluate numerical data presented in tables, charts, and graphs. Candidates interpret financial figures, percentages, and ratios to make sound business decisions.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Graduate,Mid-Level,Senior",
    languages: "English,Spanish,French,German,Dutch,Portuguese",
    skills: "Numerical Analysis,Data Interpretation,Quantitative Reasoning"
  },
  {
    name: "Verify - Verbal Reasoning",
    slug: "verify-verbal-reasoning",
    url: "https://www.shl.com/products/product-catalog/view/verify-verbal-reasoning/",
    description: "Assesses the ability to evaluate written information and draw logical conclusions from text. Candidates analyze passages to determine whether statements are true, false, or cannot be determined.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Graduate,Mid-Level,Senior,Executive",
    languages: "English,Spanish,French,German,Dutch,Portuguese",
    skills: "Verbal Comprehension,Logical Reasoning,Critical Thinking"
  },
  {
    name: "Verify - Inductive Reasoning",
    slug: "verify-inductive-reasoning",
    url: "https://www.shl.com/products/product-catalog/view/verify-inductive-reasoning/",
    description: "Measures the ability to identify patterns, rules, and relationships in data and apply them to solve problems. Candidates evaluate abstract sequences and determine underlying logic.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate,Mid-Level,Senior",
    languages: "English,Spanish,French,German",
    skills: "Pattern Recognition,Abstract Reasoning,Logical Thinking"
  },
  {
    name: "Verify - Deductive Reasoning",
    slug: "verify-deductive-reasoning",
    url: "https://www.shl.com/products/product-catalog/view/verify-deductive-reasoning/",
    description: "Evaluates the ability to draw logical conclusions from given information. Candidates analyze premises and determine which conclusions necessarily follow from the presented facts.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Graduate,Mid-Level,Senior",
    languages: "English,Spanish,French,German",
    skills: "Logical Deduction,Analytical Thinking,Problem Solving"
  },
  {
    name: "Verify - Mechanical Comprehension",
    slug: "verify-mechanical-comprehension",
    url: "https://www.shl.com/products/product-catalog/view/verify-mechanical-comprehension/",
    description: "Assesses understanding of basic mechanical principles and physical laws. Candidates analyze diagrams of mechanical systems to predict outcomes and understand cause-effect relationships.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English,Spanish,French",
    skills: "Mechanical Reasoning,Physics Understanding,Spatial Awareness"
  },
  {
    name: "Verify - Spatial Reasoning",
    slug: "verify-spatial-reasoning",
    url: "https://www.shl.com/products/product-catalog/view/verify-spatial-reasoning/",
    description: "Measures the ability to visualize and manipulate objects in three-dimensional space. Candidates mentally rotate, assemble, and disassemble shapes to solve spatial problems.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English,Spanish,French",
    skills: "Spatial Visualization,Mental Rotation,3D Reasoning"
  },
  {
    name: "Verify - Checking",
    slug: "verify-checking",
    url: "https://www.shl.com/products/product-catalog/view/verify-checking/",
    description: "Evaluates speed and accuracy in comparing information across different sources. Candidates identify discrepancies between sets of data, ensuring attention to detail and quality control.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "15 minutes",
    jobLevels: "Entry,Graduate",
    languages: "English,Spanish,French,German",
    skills: "Attention to Detail,Accuracy,Data Verification"
  },
  {
    name: "Verify - Calculation",
    slug: "verify-calculation",
    url: "https://www.shl.com/products/product-catalog/view/verify-calculation/",
    description: "Measures basic numerical computation skills including addition, subtraction, multiplication, and division. Candidates solve straightforward arithmetic problems quickly and accurately.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "15 minutes",
    jobLevels: "Entry,Graduate",
    languages: "English,Spanish,French,German",
    skills: "Arithmetic,Numerical Computation,Mathematical Fluency"
  },
  {
    name: "Verify - G+",
    slug: "verify-g-plus",
    url: "https://www.shl.com/products/product-catalog/view/verify-g-plus/",
    description: "A comprehensive general ability assessment combining numerical, verbal, and inductive reasoning. Provides a holistic measure of cognitive capability for predicting job performance.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "36 minutes",
    jobLevels: "Graduate,Mid-Level,Senior,Executive",
    languages: "English,Spanish,French,German,Dutch",
    skills: "General Mental Ability,Reasoning,Problem Solving"
  },
  {
    name: "SHL Verify Interactive - Numerical Reasoning",
    slug: "shl-verify-interactive-numerical-reasoning",
    url: "https://www.shl.com/products/product-catalog/view/shl-verify-interactive-numerical-reasoning/",
    description: "An interactive, scenario-based numerical reasoning assessment that presents candidates with realistic workplace scenarios requiring data analysis and numerical problem-solving.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: true,
    duration: "25 minutes",
    jobLevels: "Graduate,Mid-Level,Senior",
    languages: "English",
    skills: "Numerical Analysis,Data Interpretation,Business Acumen"
  },
  {
    name: "SHL Verify Interactive - Verbal Reasoning",
    slug: "shl-verify-interactive-verbal-reasoning",
    url: "https://www.shl.com/products/product-catalog/view/shl-verify-interactive-verbal-reasoning/",
    description: "An interactive verbal reasoning assessment with realistic workplace scenarios requiring evaluation of written communications and drawing conclusions from business documents.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: true,
    duration: "25 minutes",
    jobLevels: "Graduate,Mid-Level,Senior",
    languages: "English",
    skills: "Reading Comprehension,Verbal Analysis,Critical Thinking"
  },
  {
    name: "SHL Verify Interactive - Inductive Reasoning",
    slug: "shl-verify-interactive-inductive-reasoning",
    url: "https://www.shl.com/products/product-catalog/view/shl-verify-interactive-inductive-reasoning/",
    description: "Evaluates ability to identify specific patterns in data or situations and generalize that information to broader contexts through interactive, scenario-based items.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: true,
    duration: "25 minutes",
    jobLevels: "Graduate,Mid-Level,Senior",
    languages: "English",
    skills: "Pattern Recognition,Abstract Reasoning,Inductive Logic"
  },
  {
    name: "Verify - Technical Checking Next Generation",
    slug: "verify-technical-checking-next-generation",
    url: "https://www.shl.com/products/product-catalog/view/verify-technical-checking-next-generation/",
    description: "Next-generation assessment measuring speed and accuracy in detecting errors in technical data, diagrams, and specifications. Enhanced with modern item types and improved psychometrics.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "15 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English",
    skills: "Attention to Detail,Technical Accuracy,Quality Control"
  },
  {
    name: "Verify - Interactive Ability Report",
    slug: "verify-interactive-ability-report",
    url: "https://www.shl.com/products/product-catalog/view/verify-interactive-ability-report/",
    description: "A combined interactive ability assessment that generates a comprehensive report covering numerical, verbal, and inductive reasoning capabilities with detailed competency mapping.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: true,
    duration: "45 minutes",
    jobLevels: "Graduate,Mid-Level,Senior",
    languages: "English",
    skills: "Cognitive Ability,Reasoning,Analytical Thinking"
  },

  // ============================================================================
  // PERSONALITY ASSESSMENTS (P)
  // ============================================================================
  {
    name: "OPQ32r - Occupational Personality Questionnaire",
    slug: "opq32r",
    url: "https://www.shl.com/products/product-catalog/view/opq32r/",
    description: "The OPQ32r is SHL's flagship personality assessment measuring 32 dimensions of behavioral style relevant to the workplace. It provides deep insight into how an individual's personality impacts their approach to work and interactions with others.",
    testType: "P",
    category: "Personality",
    remoteTesting: true,
    adaptive: false,
    duration: "45 minutes",
    jobLevels: "Graduate,Mid-Level,Senior,Executive",
    languages: "English,Spanish,French,German,Dutch,Portuguese,Italian,Chinese,Japanese",
    skills: "Self-Awareness,Behavioral Style,Interpersonal Dynamics"
  },
  {
    name: "OPQ32n - Occupational Personality Questionnaire (Normative)",
    slug: "opq32n",
    url: "https://www.shl.com/products/product-catalog/view/opq32n/",
    description: "The normative version of the OPQ32, using a Likert-scale response format rather than ipsative (forced-choice). Measures the same 32 personality dimensions with a different response approach suited to specific reporting needs.",
    testType: "P",
    category: "Personality",
    remoteTesting: true,
    adaptive: false,
    duration: "40 minutes",
    jobLevels: "Graduate,Mid-Level,Senior,Executive",
    languages: "English,Spanish,French,German",
    skills: "Self-Awareness,Behavioral Style,Interpersonal Dynamics"
  },
  {
    name: "MQ - Motivation Questionnaire",
    slug: "mq-profile",
    url: "https://www.shl.com/products/product-catalog/view/mq-profile/",
    description: "Measures an individual's motivational drivers and what energizes or demotivates them at work. The profile chart shows Sten scores comparing the individual's motivational drivers against a norm group.",
    testType: "P",
    category: "Personality",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior,Executive",
    languages: "English,Spanish,French,German",
    skills: "Motivation,Self-Drive,Engagement"
  },
  {
    name: "OPQ Universal Competency Report 2.0",
    slug: "opq-universal-competency-report-2-0",
    url: "https://www.shl.com/products/product-catalog/view/opq-universal-competency-report-2-0/",
    description: "Provides a graphical scale for each competency and summarises aspects of personality which contribute positively or negatively to each competency. Maps OPQ32 dimensions to the Universal Competency Framework for talent management decisions.",
    testType: "P",
    category: "Personality",
    remoteTesting: true,
    adaptive: false,
    duration: "45 minutes",
    jobLevels: "Graduate,Mid-Level,Senior,Executive",
    languages: "English,Spanish,French,German",
    skills: "Competency Mapping,Leadership Potential,Development Planning"
  },
  {
    name: "OPQ Universal Competency Report",
    slug: "opq-universal-competency-report",
    url: "https://www.shl.com/products/product-catalog/view/opq-universal-competency-report/",
    description: "Based on the Universal Competency framework, this OPQ report graphically outlines how an individual's typical way of behaving may impact their performance against specific competency requirements.",
    testType: "P",
    category: "Personality",
    remoteTesting: true,
    adaptive: false,
    duration: "45 minutes",
    jobLevels: "Graduate,Mid-Level,Senior",
    languages: "English,Spanish,French,German",
    skills: "Competency Assessment,Behavioral Analysis,Talent Development"
  },
  {
    name: "OPQ Leadership Report",
    slug: "opq-leadership-report",
    url: "https://www.shl.com/products/product-catalog/view/opq-leadership-report/",
    description: "Evaluates leadership potential by mapping personality traits to key leadership competencies. Identifies strengths and development areas for leadership roles and informs succession planning.",
    testType: "P",
    category: "Personality",
    remoteTesting: true,
    adaptive: false,
    duration: "45 minutes",
    jobLevels: "Senior,Executive",
    languages: "English,Spanish,French,German",
    skills: "Leadership,Strategic Thinking,Influence"
  },
  {
    name: "OPQ Sales Report",
    slug: "opq-sales-report",
    url: "https://www.shl.com/products/product-catalog/view/opq-sales-report/",
    description: "Maps personality dimensions to critical sales competencies such as persuasion, resilience, and relationship building. Helps identify individuals with the behavioral traits associated with sales success.",
    testType: "P",
    category: "Personality",
    remoteTesting: true,
    adaptive: false,
    duration: "45 minutes",
    jobLevels: "Entry,Graduate,Mid-Level,Senior",
    languages: "English,Spanish,French",
    skills: "Sales Aptitude,Persuasion,Relationship Building"
  },
  {
    name: "OPQ Team Impact Report",
    slug: "opq-team-impact-report",
    url: "https://www.shl.com/products/product-catalog/view/opq-team-impact-report/",
    description: "Analyzes how an individual's personality impacts team dynamics and collaboration. Identifies preferred team roles and potential areas of friction within team settings.",
    testType: "P",
    category: "Personality",
    remoteTesting: true,
    adaptive: false,
    duration: "45 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English,Spanish,French",
    skills: "Teamwork,Collaboration,Communication"
  },
  {
    name: "OPQ Managerial & Professional Styles Report",
    slug: "opq-managerial-professional-styles",
    url: "https://www.shl.com/products/product-catalog/view/opq-managerial-professional-styles/",
    description: "Provides insight into the managerial and professional behavioral styles of individuals. Helps organizations understand how leaders approach decision-making, people management, and strategic challenges.",
    testType: "P",
    category: "Personality",
    remoteTesting: true,
    adaptive: false,
    duration: "45 minutes",
    jobLevels: "Mid-Level,Senior,Executive",
    languages: "English,French,German",
    skills: "Management Style,Decision Making,Strategic Orientation"
  },
  {
    name: "OPQ Candidate Report",
    slug: "opq-candidate-report",
    url: "https://www.shl.com/products/product-catalog/view/opq-candidate-report/",
    description: "A candidate-friendly OPQ report that presents personality insights in accessible language. Designed to support selection interviews and onboarding conversations.",
    testType: "P",
    category: "Personality",
    remoteTesting: true,
    adaptive: false,
    duration: "45 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English,Spanish,French,German",
    skills: "Self-Awareness,Behavioral Style,Job Fit"
  },

  // ============================================================================
  // KNOWLEDGE/SKILLS TESTS (K) - Technical
  // ============================================================================
  {
    name: ".NET Framework 4.5",
    slug: "net-framework-4-5",
    url: "https://www.shl.com/products/product-catalog/view/net-framework-4-5/",
    description: "Assesses knowledge of the .NET Framework 4.5 including the Common Language Runtime, class libraries, and application development fundamentals. Designed for developers working with Microsoft technologies.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: true,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: ".NET Framework,CLR,Application Development"
  },
  {
    name: ".NET MVC (New)",
    slug: "net-mvc-new",
    url: "https://www.shl.com/products/product-catalog/view/net-mvc-new/",
    description: "Evaluates knowledge of ASP.NET MVC framework including model-view-controller architecture, routing, controllers, views, and data access patterns for building web applications.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "ASP.NET MVC,Web Development,Routing"
  },
  {
    name: ".NET MVVM (New)",
    slug: "net-mvvm-new",
    url: "https://www.shl.com/products/product-catalog/view/net-mvvm-new/",
    description: "Tests understanding of the Model-View-ViewModel pattern in .NET applications, including data binding, commands, and separation of concerns in WPF and UWP development.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "MVVM Pattern,WPF,Data Binding"
  },
  {
    name: ".NET WCF (New)",
    slug: "net-wcf-new",
    url: "https://www.shl.com/products/product-catalog/view/net-wcf-new/",
    description: "Assesses knowledge of Windows Communication Foundation for building service-oriented applications, including contracts, bindings, endpoints, and hosting configurations.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "WCF,Service-Oriented Architecture,Distributed Systems"
  },
  {
    name: ".NET WPF (New)",
    slug: "net-wpf-new",
    url: "https://www.shl.com/products/product-catalog/view/net-wpf-new/",
    description: "Evaluates proficiency in Windows Presentation Foundation for building desktop applications, including XAML, data binding, templates, and the visual tree architecture.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "WPF,XAML,Desktop Application Development"
  },
  {
    name: ".NET XAML (New)",
    slug: "net-xaml-new",
    url: "https://www.shl.com/products/product-catalog/view/net-xaml-new/",
    description: "Measures knowledge of XAML (Extensible Application Markup Language) used for defining UI elements in .NET applications, including syntax, namespaces, and resource management.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "XAML,UI Definition,Resource Management"
  },
  {
    name: "ADO.NET (New)",
    slug: "ado-net-new",
    url: "https://www.shl.com/products/product-catalog/view/ado-net-new/",
    description: "Assesses knowledge of ADO.NET data access technology including connection management, commands, data readers, datasets, and entity framework integration.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "ADO.NET,Data Access,Database Connectivity"
  },
  {
    name: "Java 8 (New)",
    slug: "java-8-new",
    url: "https://www.shl.com/products/product-catalog/view/java-8-new/",
    description: "Evaluates proficiency in Java 8 including lambda expressions, streams, functional interfaces, and the new Date/Time API. Designed for developers building enterprise Java applications.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: true,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Java 8,Lambda Expressions,Streams API"
  },
  {
    name: "Java SE 7",
    slug: "java-se-7",
    url: "https://www.shl.com/products/product-catalog/view/java-se-7/",
    description: "Tests knowledge of Java Standard Edition 7 including core language features, collections, exception handling, I/O, and concurrency utilities.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Java SE,Collections,Exception Handling"
  },
  {
    name: "Java SE 8",
    slug: "java-se-8",
    url: "https://www.shl.com/products/product-catalog/view/java-se-8/",
    description: "Assesses Java SE 8 programming skills including functional programming concepts, stream operations, optional class, and method references for modern Java development.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Java SE 8,Functional Programming,Stream Operations"
  },
  {
    name: "Java Design Patterns (New)",
    slug: "java-design-patterns-new",
    url: "https://www.shl.com/products/product-catalog/view/java-design-patterns-new/",
    description: "Evaluates understanding of common software design patterns and their implementation in Java, including creational, structural, and behavioral patterns.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Design Patterns,Software Architecture,GoF Patterns"
  },
  {
    name: "Python (New)",
    slug: "python-new",
    url: "https://www.shl.com/products/product-catalog/view/python-new/",
    description: "Assesses Python programming skills including data types, control structures, functions, object-oriented programming, and standard library usage for general-purpose development.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: true,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Python,Object-Oriented Programming,Standard Library"
  },
  {
    name: "Python 3",
    slug: "python-3",
    url: "https://www.shl.com/products/product-catalog/view/python-3/",
    description: "Tests Python 3 programming proficiency including modern Python features, list comprehensions, generators, decorators, and context managers.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Python 3,Generators,Decorators"
  },
  {
    name: "C# (New)",
    slug: "c-sharp-new",
    url: "https://www.shl.com/products/product-catalog/view/c-sharp-new/",
    description: "Evaluates C# programming knowledge including language fundamentals, LINQ, async/await, generics, and modern C# features for building .NET applications.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: true,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "C#,LINQ,Async Programming"
  },
  {
    name: "C++ (New)",
    slug: "c-plus-plus-new",
    url: "https://www.shl.com/products/product-catalog/view/c-plus-plus-new/",
    description: "Assesses C++ programming skills including memory management, pointers, STL, templates, object-oriented design, and modern C++ standards.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "C++,Memory Management,STL"
  },
  {
    name: "SQL Server (New)",
    slug: "sql-server-new",
    url: "https://www.shl.com/products/product-catalog/view/sql-server-new/",
    description: "Evaluates SQL Server database skills including T-SQL queries, stored procedures, indexing, transactions, and performance optimization for database development and administration.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "SQL Server,T-SQL,Database Administration"
  },
  {
    name: "MySQL (New)",
    slug: "mysql-new",
    url: "https://www.shl.com/products/product-catalog/view/mysql-new/",
    description: "Assesses MySQL database proficiency including SQL queries, joins, subqueries, indexing, stored procedures, and database design principles.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "MySQL,SQL,Database Design"
  },
  {
    name: "Oracle PL/SQL",
    slug: "oracle-pl-sql",
    url: "https://www.shl.com/products/product-catalog/view/oracle-pl-sql/",
    description: "Tests Oracle PL/SQL programming skills including procedural language extensions, cursors, triggers, packages, and exception handling in Oracle database environments.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "PL/SQL,Oracle Database,Procedural Programming"
  },
  {
    name: "JavaScript (New)",
    slug: "javascript-new",
    url: "https://www.shl.com/products/product-catalog/view/javascript-new/",
    description: "Evaluates JavaScript programming skills including ES6+ features, DOM manipulation, async programming, closures, and prototypal inheritance for web development.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: true,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "JavaScript,ES6+,Async Programming"
  },
  {
    name: "TypeScript (New)",
    slug: "typescript-new",
    url: "https://www.shl.com/products/product-catalog/view/typescript-new/",
    description: "Assesses TypeScript programming proficiency including type systems, interfaces, generics, decorators, and advanced type features for building scalable applications.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "TypeScript,Type Systems,Interfaces"
  },
  {
    name: "HTML5 (New)",
    slug: "html5-new",
    url: "https://www.shl.com/products/product-catalog/view/html5-new/",
    description: "Tests HTML5 markup knowledge including semantic elements, forms, multimedia, canvas, web storage, and accessibility best practices for modern web development.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Mid-Level",
    languages: "English",
    skills: "HTML5,Semantic Markup,Web Standards"
  },
  {
    name: "CSS3 (New)",
    slug: "css3-new",
    url: "https://www.shl.com/products/product-catalog/view/css3-new/",
    description: "Evaluates CSS3 styling skills including flexbox, grid layout, animations, transitions, responsive design, and CSS preprocessors for creating modern web interfaces.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Mid-Level",
    languages: "English",
    skills: "CSS3,Responsive Design,Layout Systems"
  },
  {
    name: "Angular (New)",
    slug: "angular-new",
    url: "https://www.shl.com/products/product-catalog/view/angular-new/",
    description: "Assesses Angular framework proficiency including components, directives, services, dependency injection, routing, and reactive forms for building single-page applications.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Angular,TypeScript,SPA Development"
  },
  {
    name: "React (New)",
    slug: "react-new",
    url: "https://www.shl.com/products/product-catalog/view/react-new/",
    description: "Evaluates React library skills including JSX, hooks, state management, component lifecycle, context API, and performance optimization for building modern user interfaces.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "React,Hooks,Component Architecture"
  },
  {
    name: "Node.js (New)",
    slug: "nodejs-new",
    url: "https://www.shl.com/products/product-catalog/view/nodejs-new/",
    description: "Assesses Node.js server-side development skills including event loop, streams, modules, Express.js, middleware, and RESTful API development.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Node.js,Express.js,Server-Side Development"
  },
  {
    name: "Vue.js (New)",
    slug: "vuejs-new",
    url: "https://www.shl.com/products/product-catalog/view/vuejs-new/",
    description: "Tests Vue.js framework proficiency including reactivity, components, Vuex/Pinia state management, Vue Router, and composition API for progressive web application development.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Vue.js,Reactivity System,Component Design"
  },
  {
    name: "Django (New)",
    slug: "django-new",
    url: "https://www.shl.com/products/product-catalog/view/django-new/",
    description: "Evaluates Django web framework skills including models, views, templates, ORM, middleware, authentication, and REST framework for Python web development.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Django,Python Web Development,ORM"
  },
  {
    name: "Spring (New)",
    slug: "spring-new",
    url: "https://www.shl.com/products/product-catalog/view/spring-new/",
    description: "Assesses Spring Framework knowledge including dependency injection, Spring Boot, Spring MVC, Spring Data, and Spring Security for enterprise Java application development.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Spring Framework,Spring Boot,Dependency Injection"
  },
  {
    name: "Docker (New)",
    slug: "docker-new",
    url: "https://www.shl.com/products/product-catalog/view/docker-new/",
    description: "Tests Docker containerization skills including Dockerfiles, images, containers, volumes, networking, Docker Compose, and container orchestration basics.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Docker,Containerization,DevOps"
  },
  {
    name: "Kubernetes (New)",
    slug: "kubernetes-new",
    url: "https://www.shl.com/products/product-catalog/view/kubernetes-new/",
    description: "Evaluates Kubernetes orchestration knowledge including pods, services, deployments, ingress, config maps, secrets, and cluster management for container orchestration.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Senior",
    languages: "English",
    skills: "Kubernetes,Container Orchestration,Cluster Management"
  },
  {
    name: "Linux (New)",
    slug: "linux-new",
    url: "https://www.shl.com/products/product-catalog/view/linux-new/",
    description: "Assesses Linux system administration skills including command-line operations, file systems, permissions, process management, shell scripting, and network configuration.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Linux,System Administration,Shell Scripting"
  },
  {
    name: "AWS (New)",
    slug: "aws-new",
    url: "https://www.shl.com/products/product-catalog/view/aws-new/",
    description: "Tests Amazon Web Services knowledge including EC2, S3, RDS, Lambda, IAM, VPC, and CloudFormation for cloud infrastructure and application deployment.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "AWS,Cloud Computing,Infrastructure as Code"
  },
  {
    name: "Azure (New)",
    slug: "azure-new",
    url: "https://www.shl.com/products/product-catalog/view/azure-new/",
    description: "Evaluates Microsoft Azure cloud platform skills including virtual machines, Azure SQL, App Services, Azure Functions, and Azure DevOps for cloud solution development.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Azure,Cloud Services,Microsoft Ecosystem"
  },
  {
    name: "Go (New)",
    slug: "go-new",
    url: "https://www.shl.com/products/product-catalog/view/go-new/",
    description: "Assesses Go programming language proficiency including goroutines, channels, interfaces, error handling, and concurrency patterns for building scalable backend services.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Go,Concurrency,Microservices"
  },
  {
    name: "Rust (New)",
    slug: "rust-new",
    url: "https://www.shl.com/products/product-catalog/view/rust-new/",
    description: "Tests Rust programming skills including ownership, borrowing, lifetimes, traits, and unsafe code for building memory-safe systems-level applications.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Rust,Memory Safety,Systems Programming"
  },
  {
    name: "Scala (New)",
    slug: "scala-new",
    url: "https://www.shl.com/products/product-catalog/view/scala-new/",
    description: "Evaluates Scala programming proficiency including functional programming concepts, pattern matching, implicits, and Akka framework for building distributed systems.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Scala,Functional Programming,Distributed Systems"
  },
  {
    name: "Swift (New)",
    slug: "swift-new",
    url: "https://www.shl.com/products/product-catalog/view/swift-new/",
    description: "Assesses Swift programming skills for iOS/macOS development including optionals, protocols, closures, SwiftUI, and memory management for Apple platform development.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Swift,iOS Development,SwiftUI"
  },
  {
    name: "Kotlin (New)",
    slug: "kotlin-new",
    url: "https://www.shl.com/products/product-catalog/view/kotlin-new/",
    description: "Tests Kotlin programming proficiency including null safety, coroutines, extension functions, and Android development patterns for modern mobile application development.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Kotlin,Android Development,Coroutines"
  },
  {
    name: "Ruby (New)",
    slug: "ruby-new",
    url: "https://www.shl.com/products/product-catalog/view/ruby-new/",
    description: "Evaluates Ruby programming skills including object-oriented design, blocks, mixins, metaprogramming, and Rails framework fundamentals for web application development.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Ruby,Rails,Web Development"
  },
  {
    name: "PHP (New)",
    slug: "php-new",
    url: "https://www.shl.com/products/product-catalog/view/php-new/",
    description: "Assesses PHP programming knowledge including modern PHP features, object-oriented programming, security best practices, and Laravel/Symfony framework concepts.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "PHP,Web Development,OOP"
  },
  {
    name: "R (New)",
    slug: "r-new",
    url: "https://www.shl.com/products/product-catalog/view/r-new/",
    description: "Tests R programming proficiency for statistical computing including data manipulation, visualization with ggplot2, statistical modeling, and reproducible research practices.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "R,Statistical Computing,Data Visualization"
  },
  {
    name: "Excel (New)",
    slug: "excel-new",
    url: "https://www.shl.com/products/product-catalog/view/excel-new/",
    description: "Evaluates Microsoft Excel skills including formulas, pivot tables, charts, data validation, VLOOKUP/INDEX-MATCH, and conditional formatting for business data analysis.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English",
    skills: "Excel,Data Analysis,Spreadsheets"
  },
  {
    name: "Word (New)",
    slug: "word-new",
    url: "https://www.shl.com/products/product-catalog/view/word-new/",
    description: "Assesses Microsoft Word proficiency including document formatting, styles, templates, mail merge, tables, and collaboration features for professional document creation.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "20 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English",
    skills: "Microsoft Word,Document Formatting,Collaboration"
  },
  {
    name: "PowerPoint (New)",
    slug: "powerpoint-new",
    url: "https://www.shl.com/products/product-catalog/view/powerpoint-new/",
    description: "Tests Microsoft PowerPoint skills including slide design, animations, transitions, master slides, and multimedia integration for effective presentation creation.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "20 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English",
    skills: "PowerPoint,Presentation Design,Visual Communication"
  },
  {
    name: "Tableau (New)",
    slug: "tableau-new",
    url: "https://www.shl.com/products/product-catalog/view/tableau-new/",
    description: "Evaluates Tableau data visualization skills including creating dashboards, calculated fields, data blending, and interactive visualizations for business intelligence.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Tableau,Data Visualization,Business Intelligence"
  },
  {
    name: "Power BI (New)",
    slug: "power-bi-new",
    url: "https://www.shl.com/products/product-catalog/view/power-bi-new/",
    description: "Assesses Microsoft Power BI skills including data modeling, DAX formulas, visualizations, report design, and data transformation for business analytics.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Power BI,DAX,Business Analytics"
  },
  {
    name: "COBOL (New)",
    slug: "cobol-new",
    url: "https://www.shl.com/products/product-catalog/view/cobol-new/",
    description: "Tests COBOL programming knowledge for legacy system maintenance including program structure, data division, procedure division, and file handling in mainframe environments.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "COBOL,Mainframe,Legacy Systems"
  },
  {
    name: "SAP ABAP",
    slug: "sap-abap",
    url: "https://www.shl.com/products/product-catalog/view/sap-abap/",
    description: "Evaluates SAP ABAP programming skills including data dictionary, reports, module pools, BAPIs, and enhancement techniques for SAP application development.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "SAP ABAP,ERP Development,Business Applications"
  },
  {
    name: ".NET Core (New)",
    slug: "net-core-new",
    url: "https://www.shl.com/products/product-catalog/view/net-core-new/",
    description: "Assesses .NET Core cross-platform development skills including ASP.NET Core, middleware, dependency injection, Entity Framework Core, and cloud deployment.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: ".NET Core,ASP.NET Core,Cross-Platform Development"
  },
  {
    name: "Salesforce",
    slug: "salesforce",
    url: "https://www.shl.com/products/product-catalog/view/salesforce/",
    description: "Tests Salesforce platform knowledge including administration, configuration, Apex programming, Visualforce, and Lightning components for CRM development.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Salesforce,CRM,Apex Programming"
  },
  {
    name: "SharePoint (New)",
    slug: "sharepoint-new",
    url: "https://www.shl.com/products/product-catalog/view/sharepoint-new/",
    description: "Evaluates Microsoft SharePoint skills including site management, workflows, document libraries, web parts, and Power Automate integration for enterprise collaboration.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Mid-Level",
    languages: "English",
    skills: "SharePoint,Document Management,Workflow"
  },

  // ============================================================================
  // KNOWLEDGE/SKILLS TESTS (K) - Business/Finance
  // ============================================================================
  {
    name: "Accounts Payable (New)",
    slug: "accounts-payable-new",
    url: "https://www.shl.com/products/product-catalog/view/accounts-payable-new/",
    description: "Assesses knowledge of accounts payable processes including invoice processing, vendor management, payment terms, three-way matching, and reconciliation procedures.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English",
    skills: "Accounts Payable,Invoice Processing,Reconciliation"
  },
  {
    name: "Accounts Receivable (New)",
    slug: "accounts-receivable-new",
    url: "https://www.shl.com/products/product-catalog/view/accounts-receivable-new/",
    description: "Evaluates accounts receivable knowledge including billing, collections, credit management, aging analysis, and customer payment processing.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English",
    skills: "Accounts Receivable,Collections,Credit Management"
  },
  {
    name: "Bookkeeping (New)",
    slug: "bookkeeping-new",
    url: "https://www.shl.com/products/product-catalog/view/bookkeeping-new/",
    description: "Tests bookkeeping fundamentals including double-entry principles, journal entries, general ledger maintenance, bank reconciliation, and financial statement preparation.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate",
    languages: "English",
    skills: "Bookkeeping,Double-Entry Accounting,Financial Statements"
  },
  {
    name: "Financial Accounting (New)",
    slug: "financial-accounting-new",
    url: "https://www.shl.com/products/product-catalog/view/financial-accounting-new/",
    description: "Assesses financial accounting knowledge including GAAP/IFRS principles, financial reporting, asset valuation, liabilities, equity, and cash flow analysis.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Graduate,Mid-Level,Senior",
    languages: "English",
    skills: "Financial Accounting,GAAP,Financial Reporting"
  },
  {
    name: "Reading Comprehension v2",
    slug: "reading-comprehension-v2",
    url: "https://www.shl.com/products/product-catalog/view/reading-comprehension-v2/",
    description: "Measures the ability to read and understand written passages, extract key information, and draw accurate conclusions. Updated with modern workplace-relevant content.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "20 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English",
    skills: "Reading Comprehension,Information Extraction,Critical Analysis"
  },
  {
    name: "Reading Comprehension - Spanish v1",
    slug: "reading-comprehension-spanish-v1",
    url: "https://www.shl.com/products/product-catalog/view/reading-comprehension-spanish-v1/",
    description: "This test is comprised of items that contain a passage that must be read in order to answer the question being asked. Designed for Spanish-speaking candidates.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "20 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "Spanish",
    skills: "Reading Comprehension,Spanish Language,Information Extraction"
  },

  // ============================================================================
  // BEHAVIORAL / SITUATIONAL TESTS (B)
  // ============================================================================
  {
    name: "Situational Judgement Test - Managerial",
    slug: "situational-judgement-test-managerial",
    url: "https://www.shl.com/products/product-catalog/view/situational-judgement-test-managerial/",
    description: "Presents realistic managerial scenarios requiring candidates to evaluate and choose the most effective course of action. Measures judgment, decision-making, and leadership potential.",
    testType: "B",
    category: "Behavioral",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior,Executive",
    languages: "English,Spanish,French,German",
    skills: "Decision Making,Leadership,Problem Solving"
  },
  {
    name: "SJT - Customer Service",
    slug: "sjt-customer-service",
    url: "https://www.shl.com/products/product-catalog/view/sjt-customer-service/",
    description: "Evaluates customer service judgment through realistic scenarios involving customer interactions, complaints, and service recovery. Measures ability to balance customer needs with business requirements.",
    testType: "B",
    category: "Behavioral",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English,Spanish,French",
    skills: "Customer Service,Communication,Problem Resolution"
  },
  {
    name: "SJT - Graduate",
    slug: "sjt-graduate",
    url: "https://www.shl.com/products/product-catalog/view/sjt-graduate/",
    description: "Assesses graduate-level situational judgment with scenarios relevant to early career professionals. Measures professional judgment, teamwork, and adaptability in workplace situations.",
    testType: "B",
    category: "Behavioral",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Graduate",
    languages: "English,Spanish,French,German",
    skills: "Professional Judgment,Teamwork,Adaptability"
  },
  {
    name: "Universal Competency Framework",
    slug: "universal-competency-framework",
    url: "https://www.shl.com/products/product-catalog/view/universal-competency-framework/",
    description: "A comprehensive framework defining 20 key competencies that drive performance across job roles. Provides a common language for talent assessment and development across organizations.",
    testType: "B",
    category: "Behavioral",
    remoteTesting: true,
    adaptive: false,
    duration: "35 minutes",
    jobLevels: "Graduate,Mid-Level,Senior,Executive",
    languages: "English,Spanish,French,German",
    skills: "Competency Assessment,Talent Management,Performance Prediction"
  },
  {
    name: "Workplace Safety - Individual 7.1 (Americas)",
    slug: "workplace-safety-individual-7-1-solution",
    url: "https://www.shl.com/products/product-catalog/view/workplace-safety-individual-7-1-solution/",
    description: "Assesses behaviors and competencies foundational to safety across a wide range of jobs, including following policies and procedures, wearing protective equipment, and hazard awareness.",
    testType: "B",
    category: "Behavioral",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English,Spanish",
    skills: "Safety Awareness,Policy Compliance,Risk Management"
  },
  {
    name: "Workplace Safety - Team 7.1 (International)",
    slug: "workplace-safety-team-7-1-solution",
    url: "https://www.shl.com/products/product-catalog/view/workplace-safety-team-7-1-solution/",
    description: "Designed for entry-level positions to measure the competencies and experiences that underlie successful and safe performance in team-based safety-critical environments.",
    testType: "B",
    category: "Behavioral",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate",
    languages: "English,French,German,Spanish",
    skills: "Safety Compliance,Teamwork,Hazard Awareness"
  },

  // ============================================================================
  // SIMULATIONS (S)
  // ============================================================================
  {
    name: "Accounts Payable Simulation (New)",
    slug: "accounts-payable-simulation-new",
    url: "https://www.shl.com/products/product-catalog/view/accounts-payable-simulation-new/",
    description: "A realistic simulation of accounts payable tasks including invoice processing, vendor payment, and reconciliation within a simulated ERP environment.",
    testType: "S",
    category: "Simulation",
    remoteTesting: true,
    adaptive: false,
    duration: "40 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English",
    skills: "Accounts Payable,ERP Systems,Invoice Processing"
  },
  {
    name: "Accounts Receivable Simulation (New)",
    slug: "accounts-receivable-simulation-new",
    url: "https://www.shl.com/products/product-catalog/view/accounts-receivable-simulation-new/",
    description: "A hands-on simulation of accounts receivable processes including customer billing, payment application, collections, and aging report analysis.",
    testType: "S",
    category: "Simulation",
    remoteTesting: true,
    adaptive: false,
    duration: "40 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English",
    skills: "Accounts Receivable,Collections,Billing"
  },
  {
    name: "Coding Simulation - Java",
    slug: "coding-simulation-java",
    url: "https://www.shl.com/products/product-catalog/view/coding-simulation-java/",
    description: "A live coding environment where candidates write, compile, and test Java code to solve programming challenges. Evaluates practical coding ability in a real-world development scenario.",
    testType: "S",
    category: "Simulation",
    remoteTesting: true,
    adaptive: false,
    duration: "60 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Java Programming,Algorithm Design,Code Quality"
  },
  {
    name: "Coding Simulation - Python",
    slug: "coding-simulation-python",
    url: "https://www.shl.com/products/product-catalog/view/coding-simulation-python/",
    description: "An interactive Python coding assessment where candidates solve real-world programming problems in a live development environment with a built-in interpreter.",
    testType: "S",
    category: "Simulation",
    remoteTesting: true,
    adaptive: false,
    duration: "60 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Python Programming,Problem Solving,Algorithm Design"
  },
  {
    name: "Coding Simulation - C++",
    slug: "coding-simulation-c-plus-plus",
    url: "https://www.shl.com/products/product-catalog/view/coding-simulation-c-plus-plus/",
    description: "A real-time C++ coding assessment where candidates implement algorithms and data structures, demonstrating proficiency in memory management and efficient coding practices.",
    testType: "S",
    category: "Simulation",
    remoteTesting: true,
    adaptive: false,
    duration: "60 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "C++ Programming,Memory Management,Algorithm Implementation"
  },
  {
    name: "Smart Interview Live Coding",
    slug: "smart-interview-live-coding",
    url: "https://www.shl.com/products/product-catalog/view/smart-interview-live-coding/",
    description: "Smart Interview Live Coding is a real-time online coding interview with a compiler interface. It enables one-to-one, panel and group interviews for collaborative coding assessment.",
    testType: "S",
    category: "Simulation",
    remoteTesting: true,
    adaptive: false,
    duration: "60 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Coding,Collaborative Problem Solving,Technical Communication"
  },
  {
    name: "Call Center Simulation",
    slug: "call-center-simulation",
    url: "https://www.shl.com/products/product-catalog/view/call-center-simulation/",
    description: "Simulates a call center environment where candidates handle customer calls, navigate systems, and resolve issues. Measures multitasking, customer service, and communication skills.",
    testType: "S",
    category: "Simulation",
    remoteTesting: true,
    adaptive: false,
    duration: "40 minutes",
    jobLevels: "Entry,Graduate",
    languages: "English,Spanish",
    skills: "Customer Service,Multitasking,Communication"
  },
  {
    name: "Administrative Simulation",
    slug: "administrative-simulation",
    url: "https://www.shl.com/products/product-catalog/view/administrative-simulation/",
    description: "A workplace simulation assessing administrative competencies including email management, scheduling, document handling, and prioritization in a realistic office environment.",
    testType: "S",
    category: "Simulation",
    remoteTesting: true,
    adaptive: false,
    duration: "35 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English",
    skills: "Administration,Organization,Time Management"
  },
  {
    name: "Sales Simulation",
    slug: "sales-simulation",
    url: "https://www.shl.com/products/product-catalog/view/sales-simulation/",
    description: "An interactive simulation of sales interactions requiring candidates to demonstrate prospecting, objection handling, negotiation, and closing techniques in realistic scenarios.",
    testType: "S",
    category: "Simulation",
    remoteTesting: true,
    adaptive: false,
    duration: "40 minutes",
    jobLevels: "Entry,Graduate,Mid-Level,Senior",
    languages: "English",
    skills: "Sales,Consultative Selling,Negotiation"
  },
  {
    name: "Coding Simulation - JavaScript",
    slug: "coding-simulation-javascript",
    url: "https://www.shl.com/products/product-catalog/view/coding-simulation-javascript/",
    description: "A live JavaScript coding environment where candidates write and test code to solve web development challenges, demonstrating proficiency in front-end and back-end JavaScript.",
    testType: "S",
    category: "Simulation",
    remoteTesting: true,
    adaptive: false,
    duration: "60 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "JavaScript,Web Development,Problem Solving"
  },

  // ============================================================================
  // ABILITY TESTS (A)
  // ============================================================================
  {
    name: "General Ability Test",
    slug: "general-ability-test",
    url: "https://www.shl.com/products/product-catalog/view/general-ability-test/",
    description: "A broad measure of general cognitive ability combining verbal, numerical, and abstract reasoning items. Predicts overall job performance across a wide range of roles.",
    testType: "A",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "35 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English,Spanish,French",
    skills: "General Ability,Reasoning,Cognitive Skills"
  },
  {
    name: "Verbal Ability Test",
    slug: "verbal-ability-test",
    url: "https://www.shl.com/products/product-catalog/view/verbal-ability-test/",
    description: "Measures verbal reasoning ability through vocabulary, analogy, and comprehension items. Assesses the capacity to understand and work with written language effectively.",
    testType: "A",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "20 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English",
    skills: "Verbal Ability,Vocabulary,Comprehension"
  },
  {
    name: "Numerical Ability Test",
    slug: "numerical-ability-test",
    url: "https://www.shl.com/products/product-catalog/view/numerical-ability-test/",
    description: "Assesses numerical reasoning through mathematical problems, data interpretation, and quantitative analysis. Measures the ability to work with numbers and numerical information.",
    testType: "A",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "20 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English",
    skills: "Numerical Ability,Quantitative Reasoning,Data Analysis"
  },
  {
    name: "Clerical Checking",
    slug: "clerical-checking",
    url: "https://www.shl.com/products/product-catalog/view/clerical-checking/",
    description: "Measures speed and accuracy in checking alphanumeric data. Candidates compare strings of numbers, letters, and symbols to identify discrepancies, simulating clerical tasks.",
    testType: "A",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "10 minutes",
    jobLevels: "Entry,Graduate",
    languages: "English,Spanish,French",
    skills: "Attention to Detail,Accuracy,Speed"
  },

  // ============================================================================
  // EMOTIONAL INTELLIGENCE (E)
  // ============================================================================
  {
    name: "Emotional Intelligence Assessment",
    slug: "emotional-intelligence-assessment",
    url: "https://www.shl.com/products/product-catalog/view/emotional-intelligence-assessment/",
    description: "Measures emotional intelligence including self-awareness, self-regulation, empathy, and social skills. Evaluates the ability to perceive, understand, and manage emotions in the workplace.",
    testType: "E",
    category: "Behavioral",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior,Executive",
    languages: "English,Spanish,French",
    skills: "Emotional Intelligence,Self-Awareness,Empathy"
  },
  {
    name: "Leadership Effectiveness Report",
    slug: "leadership-effectiveness-report",
    url: "https://www.shl.com/products/product-catalog/view/leadership-effectiveness-report/",
    description: "Provides a comprehensive assessment of leadership effectiveness combining personality, cognitive, and behavioral data. Identifies leadership strengths and development areas for executive development.",
    testType: "E",
    category: "Behavioral",
    remoteTesting: true,
    adaptive: false,
    duration: "45 minutes",
    jobLevels: "Senior,Executive",
    languages: "English,French,German",
    skills: "Leadership Effectiveness,Self-Regulation,Social Intelligence"
  },

  // ============================================================================
  // DEVELOPMENT (D)
  // ============================================================================
  {
    name: "Development Needs Report",
    slug: "development-needs-report",
    url: "https://www.shl.com/products/product-catalog/view/development-needs-report/",
    description: "Identifies specific development areas based on assessment results, providing targeted recommendations for learning and growth. Maps competency gaps to actionable development plans.",
    testType: "D",
    category: "Development",
    remoteTesting: true,
    adaptive: false,
    duration: "15 minutes",
    jobLevels: "Graduate,Mid-Level,Senior,Executive",
    languages: "English,Spanish,French,German",
    skills: "Development Planning,Competency Gap Analysis,Self-Improvement"
  },
  {
    name: "Coaching Report",
    slug: "coaching-report",
    url: "https://www.shl.com/products/product-catalog/view/coaching-report/",
    description: "Generates a detailed coaching report based on assessment outcomes, highlighting behavioral tendencies and providing coaching strategies for managers and mentors.",
    testType: "D",
    category: "Development",
    remoteTesting: true,
    adaptive: false,
    duration: "15 minutes",
    jobLevels: "Mid-Level,Senior,Executive",
    languages: "English,Spanish,French",
    skills: "Coaching,Feedback,Development Strategy"
  },

  // ============================================================================
  // COMBINED / COMPREHENSIVE ASSESSMENTS
  // ============================================================================
  {
    name: "Global Skills Development Report",
    slug: "global-skills-development-report",
    url: "https://www.shl.com/products/product-catalog/view/global-skills-development-report/",
    description: "A comprehensive multi-dimensional assessment combining ability, emotional intelligence, behavioral, cognitive, development, and personality measures. Provides a holistic view of an individual's skills and development needs.",
    testType: "A,E,B,C,D,P",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "90 minutes",
    jobLevels: "Graduate,Mid-Level,Senior,Executive",
    languages: "English,Spanish,French,German",
    skills: "Comprehensive Assessment,Skills Mapping,Development Planning"
  },
  {
    name: "360° Multi-Rater Feedback System (MFS)",
    slug: "360-multi-rater-feedback-system-mfs",
    url: "https://www.shl.com/products/product-catalog/view/360-multi-rater-feedback-system-mfs/",
    description: "SHL 360, or the Multi-Rater Feedback System (MFS), provides a holistic 360-degree view of an employee by gathering feedback from the employee's manager, peers, direct reports, and others.",
    testType: "B",
    category: "Behavioral",
    remoteTesting: true,
    adaptive: false,
    duration: "20 minutes",
    jobLevels: "Mid-Level,Senior,Executive",
    languages: "English,Spanish,French,German",
    skills: "360 Feedback,Self-Awareness,Multi-Source Assessment"
  },

  // ============================================================================
  // PRE-PACKAGED SOLUTIONS / JOB-SPECIFIC
  // ============================================================================
  {
    name: "Account Manager Solution",
    slug: "account-manager-solution",
    url: "https://www.shl.com/products/product-catalog/view/account-manager-solution/",
    description: "A pre-packaged assessment solution for account manager roles, combining cognitive ability, personality, and situational judgment measures to predict performance in client relationship management.",
    testType: "C,P,B",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "65 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English,Spanish,French",
    skills: "Account Management,Client Relations,Strategic Planning"
  },
  {
    name: "Administrative Professional Short Form",
    slug: "administrative-professional-short-form",
    url: "https://www.shl.com/products/product-catalog/view/administrative-professional-short-form/",
    description: "An abbreviated assessment for administrative roles measuring checking, numerical ability, and clerical skills. Designed for high-volume screening of administrative candidates.",
    testType: "C,A",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate",
    languages: "English",
    skills: "Administration,Attention to Detail,Clerical Skills"
  },
  {
    name: "Cashier Solution",
    slug: "cashier-solution",
    url: "https://www.shl.com/products/product-catalog/view/cashier-solution/",
    description: "A targeted assessment for cashier positions measuring numerical ability, attention to detail, and customer service orientation for retail and banking environments.",
    testType: "C,B",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Entry",
    languages: "English,Spanish",
    skills: "Numerical Accuracy,Customer Service,Attention to Detail"
  },
  {
    name: "Branch Manager Short Form",
    slug: "branch-manager-short-form",
    url: "https://www.shl.com/products/product-catalog/view/branch-manager-short-form/",
    description: "A concise assessment for branch manager roles combining leadership potential, numerical reasoning, and personality measures for banking and retail management positions.",
    testType: "C,P",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "40 minutes",
    jobLevels: "Senior",
    languages: "English",
    skills: "Leadership,Branch Management,Financial Acumen"
  },
  {
    name: "Apprentice 8.0 Job Focused Assessment",
    slug: "apprentice-8-0-job-focused-assessment",
    url: "https://www.shl.com/products/product-catalog/view/apprentice-8-0-job-focused-assessment/",
    description: "A job-focused assessment for apprenticeship programs measuring foundational cognitive ability, mechanical reasoning, and workplace behavioral tendencies for entry-level talent identification.",
    testType: "C,B",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "35 minutes",
    jobLevels: "Entry",
    languages: "English,French,German",
    skills: "Apprentice Assessment,Foundational Skills,Workplace Readiness"
  },
  {
    name: "Bilingual Spanish Reservation Agent Solution",
    slug: "bilingual-spanish-reservation-agent-solution",
    url: "https://www.shl.com/products/product-catalog/view/bilingual-spanish-reservation-agent-solution/",
    description: "Assessment for bilingual Spanish-English reservation agent roles, measuring language proficiency, customer service skills, and data entry accuracy in both languages.",
    testType: "C,B",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Entry,Graduate",
    languages: "English,Spanish",
    skills: "Bilingual Communication,Customer Service,Data Entry"
  },
  {
    name: "Bank Administrative Assistant Short Form",
    slug: "bank-administrative-assistant-short-form",
    url: "https://www.shl.com/products/product-catalog/view/bank-administrative-assistant-short-form/",
    description: "A targeted assessment for bank administrative assistant roles measuring checking accuracy, numerical ability, and attention to detail specific to banking operations.",
    testType: "C,A",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate",
    languages: "English",
    skills: "Banking Operations,Accuracy,Administrative Skills"
  },
  {
    name: "Bank Collections Agent Short Form",
    slug: "bank-collections-agent-short-form",
    url: "https://www.shl.com/products/product-catalog/view/bank-collections-agent-short-form/",
    description: "Assessment for bank collections agent positions measuring numerical reasoning, negotiation aptitude, and customer communication skills for debt recovery operations.",
    testType: "C,B",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Entry,Graduate",
    languages: "English",
    skills: "Collections,Negotiation,Numerical Reasoning"
  },
  {
    name: "Bank Operations Supervisor Short Form",
    slug: "bank-operations-supervisor-short-form",
    url: "https://www.shl.com/products/product-catalog/view/bank-operations-supervisor-short-form/",
    description: "A supervisory assessment for banking operations roles combining leadership potential, operational reasoning, and personality assessment for management positions in banking.",
    testType: "C,P",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "40 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Bank Operations,Supervisory Skills,Decision Making"
  },
  {
    name: "Agency Manager Solution",
    slug: "agency-manager-solution",
    url: "https://www.shl.com/products/product-catalog/view/agency-manager-solution/",
    description: "A comprehensive assessment for agency manager roles measuring sales leadership, strategic thinking, team management, and business development capabilities.",
    testType: "C,P,B",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "60 minutes",
    jobLevels: "Senior",
    languages: "English",
    skills: "Agency Management,Sales Leadership,Business Development"
  },
  {
    name: "Bookkeeping/Accounting/Auditing Clerk Short Form",
    slug: "bookkeeping-accounting-auditing-clerk-short-form",
    url: "https://www.shl.com/products/product-catalog/view/bookkeeping-accounting-auditing-clerk-short-form/",
    description: "A short-form assessment for bookkeeping and accounting clerk positions measuring numerical accuracy, attention to detail, and basic accounting knowledge.",
    testType: "C,K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate",
    languages: "English",
    skills: "Bookkeeping,Accounting,Numerical Accuracy"
  },

  // ============================================================================
  // ADDITIONAL TECHNICAL / SPECIALIZED
  // ============================================================================
  {
    name: "Cybersecurity (New)",
    slug: "cybersecurity-new",
    url: "https://www.shl.com/products/product-catalog/view/cybersecurity-new/",
    description: "Assesses cybersecurity knowledge including threat analysis, vulnerability assessment, security protocols, incident response, and compliance frameworks for IT security roles.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Cybersecurity,Threat Analysis,Security Protocols"
  },
  {
    name: "Data Science (New)",
    slug: "data-science-new",
    url: "https://www.shl.com/products/product-catalog/view/data-science-new/",
    description: "Evaluates data science skills including statistical analysis, machine learning fundamentals, data wrangling, and model evaluation for data-driven decision making.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "35 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Data Science,Machine Learning,Statistics"
  },
  {
    name: "Agile/Scrum (New)",
    slug: "agile-scrum-new",
    url: "https://www.shl.com/products/product-catalog/view/agile-scrum-new/",
    description: "Tests knowledge of Agile methodologies and Scrum framework including sprint planning, backlog management, daily standups, retrospectives, and continuous improvement practices.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Agile,Scrum,Project Management"
  },
  {
    name: "Project Management (New)",
    slug: "project-management-new",
    url: "https://www.shl.com/products/product-catalog/view/project-management-new/",
    description: "Assesses project management knowledge including planning, risk management, stakeholder communication, budgeting, and project lifecycle management methodologies.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Project Management,Risk Assessment,Stakeholder Management"
  },
  {
    name: "Business Analysis (New)",
    slug: "business-analysis-new",
    url: "https://www.shl.com/products/product-catalog/view/business-analysis-new/",
    description: "Evaluates business analysis competencies including requirements gathering, process modeling, stakeholder analysis, and solution evaluation for business transformation projects.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Business Analysis,Requirements Engineering,Process Modeling"
  },
  {
    name: "DevOps (New)",
    slug: "devops-new",
    url: "https://www.shl.com/products/product-catalog/view/devops-new/",
    description: "Assesses DevOps knowledge including CI/CD pipelines, infrastructure as code, monitoring, automated testing, and deployment strategies for modern software delivery.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "DevOps,CI/CD,Infrastructure as Code"
  },
  {
    name: "SAP (New)",
    slug: "sap-new",
    url: "https://www.shl.com/products/product-catalog/view/sap-new/",
    description: "Tests general SAP platform knowledge including navigation, modules (FI, CO, MM, SD, PP), integration points, and business process mapping for ERP consultants and users.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "SAP,ERP,Business Process Integration"
  },
  {
    name: "Microsoft Azure DevOps (New)",
    slug: "microsoft-azure-devops-new",
    url: "https://www.shl.com/products/product-catalog/view/microsoft-azure-devops-new/",
    description: "Evaluates Azure DevOps proficiency including Azure Repos, Pipelines, Boards, Test Plans, and Artifacts for end-to-end DevOps workflows on the Microsoft platform.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Azure DevOps,CI/CD,Microsoft ALM"
  },
  {
    name: "React Native (New)",
    slug: "react-native-new",
    url: "https://www.shl.com/products/product-catalog/view/react-native-new/",
    description: "Assesses React Native mobile development skills including component architecture, navigation, state management, native modules, and cross-platform deployment strategies.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "React Native,Mobile Development,Cross-Platform"
  },
  {
    name: "GraphQL (New)",
    slug: "graphql-new",
    url: "https://www.shl.com/products/product-catalog/view/graphql-new/",
    description: "Tests GraphQL API development skills including schema design, queries, mutations, subscriptions, resolvers, and integration with REST APIs for modern API development.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "GraphQL,API Design,Schema Definition"
  },
  {
    name: "Terraform (New)",
    slug: "terraform-new",
    url: "https://www.shl.com/products/product-catalog/view/terraform-new/",
    description: "Evaluates Terraform Infrastructure as Code skills including HCL syntax, provider configuration, state management, modules, and multi-cloud deployment strategies.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Terraform,IaC,Cloud Infrastructure"
  },
  {
    name: "Machine Learning (New)",
    slug: "machine-learning-new",
    url: "https://www.shl.com/products/product-catalog/view/machine-learning-new/",
    description: "Assesses machine learning knowledge including supervised/unsupervised learning, neural networks, model evaluation, feature engineering, and practical ML deployment considerations.",
    testType: "K",
    category: "Technical",
    remoteTesting: true,
    adaptive: false,
    duration: "35 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Machine Learning,Model Development,Feature Engineering"
  },
  {
    name: "Digital Marketing (New)",
    slug: "digital-marketing-new",
    url: "https://www.shl.com/products/product-catalog/view/digital-marketing-new/",
    description: "Tests digital marketing knowledge including SEO, SEM, social media strategy, content marketing, analytics, and campaign optimization for online marketing roles.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Mid-Level,Senior",
    languages: "English",
    skills: "Digital Marketing,SEO/SEM,Analytics"
  },
  {
    name: "Customer Experience (New)",
    slug: "customer-experience-new",
    url: "https://www.shl.com/products/product-catalog/view/customer-experience-new/",
    description: "Evaluates customer experience management skills including journey mapping, NPS analysis, voice of customer programs, and CX strategy for customer-centric organizations.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Customer Experience,Journey Mapping,CX Strategy"
  },
  {
    name: "HR Fundamentals (New)",
    slug: "hr-fundamentals-new",
    url: "https://www.shl.com/products/product-catalog/view/hr-fundamentals-new/",
    description: "Assesses foundational HR knowledge including employment law, recruitment, performance management, compensation, and employee relations for human resources professionals.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English",
    skills: "Human Resources,Employment Law,People Management"
  },
  {
    name: "Supply Chain Management (New)",
    slug: "supply-chain-management-new",
    url: "https://www.shl.com/products/product-catalog/view/supply-chain-management-new/",
    description: "Tests supply chain management knowledge including procurement, logistics, inventory management, demand planning, and supplier relationship management.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Supply Chain,Procurement,Logistics"
  },
  {
    name: "Financial Analysis (New)",
    slug: "financial-analysis-new",
    url: "https://www.shl.com/products/product-catalog/view/financial-analysis-new/",
    description: "Evaluates financial analysis skills including ratio analysis, DCF valuation, financial modeling, risk assessment, and investment analysis for finance professionals.",
    testType: "K",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "Financial Analysis,Valuation,Financial Modeling"
  },

  // ============================================================================
  // ADDITIONAL ASSESSMENTS (to reach 150+)
  // ============================================================================
  {
    name: "Verify - G+ General Ability Screen",
    slug: "verify-g-general-ability-screen",
    url: "https://www.shl.com/products/product-catalog/view/verify-g-general-ability-screen/",
    description: "A screening version of the Verify G+ assessment providing a quick measure of general cognitive ability for high-volume candidate filtering and early-stage selection.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "18 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English,Spanish,French,German",
    skills: "General Ability,Cognitive Screening,Reasoning"
  },
  {
    name: "OPQ32 Emotional Intelligence Report",
    slug: "opq32-emotional-intelligence-report",
    url: "https://www.shl.com/products/product-catalog/view/opq32-emotional-intelligence-report/",
    description: "Maps OPQ32 personality dimensions to emotional intelligence competencies, providing insight into how an individual perceives, understands, and manages emotions in themselves and others.",
    testType: "P,E",
    category: "Personality",
    remoteTesting: true,
    adaptive: false,
    duration: "45 minutes",
    jobLevels: "Mid-Level,Senior,Executive",
    languages: "English,Spanish,French",
    skills: "Emotional Intelligence,Self-Awareness,Social Skills"
  },
  {
    name: "SJT - Call Center",
    slug: "sjt-call-center",
    url: "https://www.shl.com/products/product-catalog/view/sjt-call-center/",
    description: "Evaluates situational judgment for call center roles through realistic customer interaction scenarios. Measures ability to handle difficult callers, follow procedures, and maintain service quality.",
    testType: "B",
    category: "Behavioral",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate",
    languages: "English,Spanish",
    skills: "Call Center Operations,Customer Service,Problem Resolution"
  },
  {
    name: "SJT - Sales Professional",
    slug: "sjt-sales-professional",
    url: "https://www.shl.com/products/product-catalog/view/sjt-sales-professional/",
    description: "Assesses judgment in sales scenarios including prospecting, objection handling, negotiation, and closing. Measures commercial awareness and customer-oriented selling behaviors.",
    testType: "B",
    category: "Behavioral",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate,Mid-Level,Senior",
    languages: "English,Spanish,French",
    skills: "Sales Judgment,Consultative Selling,Commercial Awareness"
  },
  {
    name: "Verify - Numerical Reasoning Next Generation",
    slug: "verify-numerical-reasoning-next-generation",
    url: "https://www.shl.com/products/product-catalog/view/verify-numerical-reasoning-next-generation/",
    description: "Next-generation numerical reasoning assessment with enhanced item types, improved psychometrics, and updated content reflecting contemporary business contexts and data formats.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Graduate,Mid-Level,Senior",
    languages: "English,Spanish,French,German",
    skills: "Numerical Reasoning,Data Analysis,Quantitative Problem Solving"
  },
  {
    name: "Verify - Verbal Reasoning Next Generation",
    slug: "verify-verbal-reasoning-next-generation",
    url: "https://www.shl.com/products/product-catalog/view/verify-verbal-reasoning-next-generation/",
    description: "Next-generation verbal reasoning assessment with modernized content, improved item design, and enhanced predictive validity for evaluating written communication comprehension.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Graduate,Mid-Level,Senior,Executive",
    languages: "English,Spanish,French,German",
    skills: "Verbal Reasoning,Reading Comprehension,Critical Analysis"
  },
  {
    name: "Coding Simulation - C#",
    slug: "coding-simulation-c-sharp",
    url: "https://www.shl.com/products/product-catalog/view/coding-simulation-c-sharp/",
    description: "A live C# coding environment where candidates write, compile, and test code to solve programming challenges. Evaluates practical .NET development skills and algorithm design.",
    testType: "S",
    category: "Simulation",
    remoteTesting: true,
    adaptive: false,
    duration: "60 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "C# Programming,.NET Development,Algorithm Design"
  },
  {
    name: "Coding Simulation - SQL",
    slug: "coding-simulation-sql",
    url: "https://www.shl.com/products/product-catalog/view/coding-simulation-sql/",
    description: "An interactive SQL assessment where candidates write queries against live databases to solve data retrieval and manipulation problems in a realistic database environment.",
    testType: "S",
    category: "Simulation",
    remoteTesting: true,
    adaptive: false,
    duration: "45 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English",
    skills: "SQL,Database Queries,Data Manipulation"
  },
  {
    name: "MQ - Motivation Questionnaire Extended",
    slug: "mq-extended",
    url: "https://www.shl.com/products/product-catalog/view/mq-extended/",
    description: "Extended version of the Motivation Questionnaire providing deeper analysis of motivational drivers, workplace preferences, and factors affecting engagement and retention.",
    testType: "P",
    category: "Personality",
    remoteTesting: true,
    adaptive: false,
    duration: "40 minutes",
    jobLevels: "Mid-Level,Senior,Executive",
    languages: "English,French,German",
    skills: "Motivation,Employee Engagement,Retention"
  },
  {
    name: "OPQ Developer Report",
    slug: "opq-developer-report",
    url: "https://www.shl.com/products/product-catalog/view/opq-developer-report/",
    description: "Provides a development-focused OPQ report identifying behavioral strengths and areas for growth. Includes actionable development suggestions aligned to career progression goals.",
    testType: "P,D",
    category: "Personality",
    remoteTesting: true,
    adaptive: false,
    duration: "45 minutes",
    jobLevels: "Graduate,Mid-Level,Senior",
    languages: "English,French,German",
    skills: "Development Planning,Behavioral Change,Self-Improvement"
  },
  {
    name: "SJT - Managerial & Professional",
    slug: "sjt-managerial-professional",
    url: "https://www.shl.com/products/product-catalog/view/sjt-managerial-professional/",
    description: "Assesses managerial and professional judgment through scenarios involving team management, strategic decisions, stakeholder management, and ethical dilemmas in leadership roles.",
    testType: "B",
    category: "Behavioral",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Mid-Level,Senior,Executive",
    languages: "English,Spanish,French,German",
    skills: "Managerial Judgment,Strategic Thinking,Ethical Decision Making"
  },
  {
    name: "Verify - Inductive Reasoning Next Generation",
    slug: "verify-inductive-reasoning-next-generation",
    url: "https://www.shl.com/products/product-catalog/view/verify-inductive-reasoning-next-generation/",
    description: "Next-generation inductive reasoning assessment with refreshed visual items and improved measurement precision for evaluating pattern recognition and abstract reasoning ability.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Entry,Graduate,Mid-Level,Senior",
    languages: "English,Spanish,French,German",
    skills: "Inductive Reasoning,Pattern Recognition,Abstract Thinking"
  },
  {
    name: "Verify - Deductive Reasoning Next Generation",
    slug: "verify-deductive-reasoning-next-generation",
    url: "https://www.shl.com/products/product-catalog/view/verify-deductive-reasoning-next-generation/",
    description: "Next-generation deductive reasoning assessment with updated scenarios and enhanced psychometric properties for measuring logical deduction and analytical thinking skills.",
    testType: "C",
    category: "Cognitive",
    remoteTesting: true,
    adaptive: false,
    duration: "25 minutes",
    jobLevels: "Graduate,Mid-Level,Senior",
    languages: "English,Spanish,French,German",
    skills: "Deductive Reasoning,Logical Analysis,Problem Solving"
  },
  {
    name: "Bank Teller Solution",
    slug: "bank-teller-solution",
    url: "https://www.shl.com/products/product-catalog/view/bank-teller-solution/",
    description: "A comprehensive assessment for bank teller positions measuring numerical accuracy, customer service aptitude, attention to detail, and cash handling skills.",
    testType: "C,B",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "35 minutes",
    jobLevels: "Entry,Graduate",
    languages: "English,Spanish",
    skills: "Banking,Numerical Accuracy,Customer Service"
  },
  {
    name: "Retail Sales Solution",
    slug: "retail-sales-solution",
    url: "https://www.shl.com/products/product-catalog/view/retail-sales-solution/",
    description: "A targeted assessment for retail sales roles measuring customer service orientation, sales aptitude, numerical reasoning, and personality traits associated with retail success.",
    testType: "C,P,B",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "45 minutes",
    jobLevels: "Entry,Graduate,Mid-Level",
    languages: "English,Spanish,French",
    skills: "Retail Sales,Customer Service,Sales Aptitude"
  },
  {
    name: "Warehouse & Logistics Solution",
    slug: "warehouse-logistics-solution",
    url: "https://www.shl.com/products/product-catalog/view/warehouse-logistics-solution/",
    description: "Assessment for warehouse and logistics roles measuring spatial reasoning, checking accuracy, safety awareness, and ability to follow procedures in distribution environments.",
    testType: "C,B",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "30 minutes",
    jobLevels: "Entry,Graduate",
    languages: "English,Spanish",
    skills: "Warehouse Operations,Safety Compliance,Spatial Reasoning"
  },
  {
    name: "OPQ Team Development Report",
    slug: "opq-team-development-report",
    url: "https://www.shl.com/products/product-catalog/view/opq-team-development-report/",
    description: "Analyzes team composition using OPQ data to identify team strengths, potential blind spots, and areas for development. Supports team building and composition optimization.",
    testType: "P,D",
    category: "Personality",
    remoteTesting: true,
    adaptive: false,
    duration: "45 minutes",
    jobLevels: "Mid-Level,Senior",
    languages: "English,French,German",
    skills: "Team Development,Team Dynamics,Collaboration"
  },
  {
    name: "Graduate Assessment Solution",
    slug: "graduate-assessment-solution",
    url: "https://www.shl.com/products/product-catalog/view/graduate-assessment-solution/",
    description: "A comprehensive graduate assessment combining cognitive ability, personality, and situational judgment measures to identify high-potential candidates for graduate development programs.",
    testType: "C,P,B",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "75 minutes",
    jobLevels: "Graduate",
    languages: "English,Spanish,French,German",
    skills: "Graduate Potential,Cognitive Ability,Leadership Readiness"
  },
  {
    name: "Executive Assessment Solution",
    slug: "executive-assessment-solution",
    url: "https://www.shl.com/products/product-catalog/view/executive-assessment-solution/",
    description: "A comprehensive assessment for executive-level positions combining strategic thinking, leadership personality, emotional intelligence, and decision-making for C-suite selection.",
    testType: "C,P,E,B",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "90 minutes",
    jobLevels: "Executive",
    languages: "English,French,German",
    skills: "Executive Leadership,Strategic Thinking,Decision Making"
  },
  {
    name: "Contact Center Agent Solution",
    slug: "contact-center-agent-solution",
    url: "https://www.shl.com/products/product-catalog/view/contact-center-agent-solution/",
    description: "A multi-faceted assessment for contact center agents measuring verbal ability, customer service orientation, multitasking, and problem-solving in high-volume communication environments.",
    testType: "C,B",
    category: "Skills",
    remoteTesting: true,
    adaptive: false,
    duration: "35 minutes",
    jobLevels: "Entry,Graduate",
    languages: "English,Spanish",
    skills: "Contact Center,Communication,Problem Solving"
  },
];

async function main() {
  console.log(`Seeding ${assessments.length} assessments...`);

  // Clear existing data
  await db.assessment.deleteMany({});

  // Insert all assessments
  for (const assessment of assessments) {
    await db.assessment.create({
      data: assessment,
    });
  }

  console.log(`Successfully seeded ${assessments.length} assessments!`);

  // Summary by category
  const categoryCounts: Record<string, number> = {};
  for (const a of assessments) {
    const cats = a.category.split(',');
    for (const cat of cats) {
      categoryCounts[cat.trim()] = (categoryCounts[cat.trim()] || 0) + 1;
    }
  }
  console.log('\nCategory breakdown:');
  for (const [cat, count] of Object.entries(categoryCounts).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${cat}: ${count}`);
  }

  // Summary by test type
  const typeCounts: Record<string, number> = {};
  for (const a of assessments) {
    const types = a.testType.split(',');
    for (const t of types) {
      const key = t.trim();
      const label: Record<string, string> = {
        'K': 'Knowledge',
        'C': 'Cognitive',
        'P': 'Personality',
        'B': 'Behavioral',
        'S': 'Simulation',
        'A': 'Ability',
        'E': 'Emotional Intelligence',
        'D': 'Development',
      };
      const name = label[key] || key;
      typeCounts[name] = (typeCounts[name] || 0) + 1;
    }
  }
  console.log('\nTest type breakdown:');
  for (const [type, count] of Object.entries(typeCounts).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${type}: ${count}`);
  }
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
